@startuml acquire_physiological_data

!$num = 1

floating note
<<complexity>>
low
----
<<frequency>>
(1HR/15min + 1 BP/144min + 1OS/30min + 1Temp/120 min + 1ECG/120 min)

\#npatient * 0,002/sec or
\#npatient * 5/15min simultaneous peak
end note


start
:A$num - Acquire Physiological Data; <<input>>
:I$num : Physiological Data; <<task>>
:\t<<buffer>>
I$num.1 : Physiological Data
\t{1..*}; <<task>>
!$num = $num + 1

fork
  :A$num - Store Data;
  :I$num.1 : <<datastore>>
  Physiological Data; <<task>>
  stop
fork again
  :Send to HandlePatientData; <<output>>
  note left
  Patient Data Handler
  end note
  stop
end fork

@enduml
