@startuml acquire_daily_activity_data


!$num = 1

floating note
<<complexity>>
low
----
<<frequency>>
#npatient*18/day or
#npatient*1/80 min or
#npatient*1/0,0002 sec
end note

start
:A$num - Acquire Daily Activity Data; <<input>>
:I$num : Daily Activity Data; <<task>>
:\t<<buffer>>
I$num.1 : Daily Activity Data
\t{1..*}; <<task>>
!$num = $num + 1
fork
  :A$num - Store Data;
  :I$num.1 : <<datastore>>
  Daily Activity Data; <<task>>
  stop
fork again
  :Send to HandlePatientData; <<output>>
  note left
  Patient Data Handler
  end note
stop
end fork

@enduml
