@startuml define_therapeutic_plan

!$num = 1

floating note
we assume we can update sensor at anytime
....
<<complexity>>
medium
----
<<frequency>>
\#nAttendingPhysician * 2/hour
end note

start
:A$num - Define Therapeutic Plan; <<acceptEvent>>
:I$num : Therapeutic Plan; <<task>>
!$num = $num + 1

:\t<<buffer>>\n I$num.2 : Physiological Sensor Frequency\n{1..*}; <<task>>

:A$num Update Sensor Frequencies;
!$num = $num + 1
:A$num - Store Therapeutic Plan;
:\t<<datastore>>\n I$num.1 : Therapeutic Plan\n{1..*}; <<task>>

stop

@enduml
