@startuml define_therapeutic_plan

!$num = 1

floating note
we assume we can update sensor at anytime
....
<<complexity>>
medium
----
<<frequency>>
\#nAttendingPhysician * 2/hour
end note

start
:A$num - Define Therapeutic Plan; <<acceptEvent>>
:I$num : Therapeutic Plan; <<task>>
!$num = $num + 1

fork
  :A$num - Store Therapeutic Plan;
  :\t<<datastore>>\n I$num.1 : Therapeutic Plan\n{1..*}; <<task>>
fork again
  :\t<<buffer>>\n I$num.2 : Physiological Sensor Frequency\n{1..*}; <<task>>

  :Send to UpdateSensorFrequencies; <<output>>
  note left
  Update Sensor Handler
  end note
end merge

stop

@enduml
