@startuml define_therapeutic_plan
' <style>
'   .input, .object, .output {
'     BackgroundColor DodgerBlue
'   }
'   .datastore {
'     BackgroundColor IndianRed
'   }
'   .buffer {
'     BackgroundColor magenta
'   }
'   .data {
'     BackgroundColor PaleGreen
'   }
' </style>

!$num = 1

floating note
we assume we can update sensor at anytime
....
<<complexity>>
medium
----
<<frequency>>
We assume it's the same as defining a new one
\#nAttendingPhysician * 2/hour
end note

start
:A$num - Get Therapeutic Plan; <<acceptEvent>>
:\t<<datastore>>\n I$num.1 : Therapeutic Plan\n{1..*}; <<datastore>> <<task>>
:I$num : Therapeutic Plan; <<data>> <<task>>
!$num = $num + 1
:A$num - Modify therapeutic plan;
!$num = $num + 1

if (Updated Physiological Sensor Frequencies?) is (yes) then
  :A$num Update Sensor Frequencies;
  !$num = $num + 1
else (no)
endif
:A$num - Store Therapeutic Plan;
:\t<<datastore>>\n I$num.1 : Therapeutic Plan\n{1..*}; <<datastore>> <<task>>

stop

@enduml
