@startuml define_therapeutic_plan

!$num = 1

floating note
we assume we can update sensor at anytime
....
<<complexity>>
medium
----
<<frequency>>
gets used by both acquire use cases, so

\#npatient*6/15min at peak
end note

start

:A$num - TODO; <<acceptEvent>>
:I$num : DATA; <<task>>
!$num = $num + 1
: TODO;
: TODO;
: TODO;
fork
: TODO;
fork again
: TODO;
fork again
: TODO;
fork again
: TODO;
end fork


stop

@enduml
