@startuml send_patient_data

!$num = 1

floating note
<<complexity>>
low
----
' same as send physiological
<<frequency>>
6000/day 
end note

start
:A$num - Send Patient Health Information; <<acceptEvent>>
:I$num : Patient Data; <<task>>
:\t<<buffer>>
I$num.1 : Patient Data
\t{1..*}; <<task>>
!$num = $num + 1
:A$num - Store Data;
:I$num.1 : <<datastore>>
Patient Data; <<task>>
stop
@enduml
