@startuml verify_exercise_compliance

!$num = 1

floating note
<<complexity>>
low
----
<<frequency>>
1/day
end note

' cron timer every day at 00:00
' get all patients
' get all patients' daily activity data
' verify
' generate report or notify attending physician

:\t\t\t\t\t\tCron: every day at 00:00; <<time-event>>
:A$num - Verify exercise compliance; <<acceptEvent>>
!$num = $num + 1
:A$num Get all Patient(s);
:\t<<datastore>>
I$num.1: Patient
\t{1..*}; <<task>>
:I$num : Patient
\t{1..*}; <<task>>
!$num = $num + 1

:A$num Get Daily Activity;
:\t<<datastore>>
I$num.1: Daily Activity
\t{1..*}; <<task>>
:I$num : Daily Activity; <<task>>
!$num = $num + 1

:A$num - Verify activity;
!$num = $num + 1
if (Activity not compliant) is (yes) then
  :I$num : ThresholdAlert; <<task>>
  :A$num - Send threshold alarm; <<output>>
else (no)
endif

stop
@enduml
