@startuml attending_phy_handler

skinparam sequence {
  ArrowColor Gray
  LifeLineBorderColor Gray
  LifeLineBackgroundColor WhiteSmoke

  ActorBorderColor Tomato
  ActorBackgroundColor LightSalmon

  ParticipantBackgroundColor PowderBlue
  ParticipantBorderColor CornflowerBlue
}
skinparam DatabaseBorderColor SeaGreen
skinparam DatabaseBackgroundColor PaleGreen

actor PhysiologicalSensor as PS
actor AttendingPhysician
participant AttendingPhysicianHandler as APH
database MedicalRecordDS
database ThresholdAlertDS

AttendingPhysician -> APH ++ : viewMedicalRecord(Patient)
APH -> MedicalRecordDS ++ : getMedicalRecord(Patient)
APH <- MedicalRecordDS -- : MedicalRecord

AttendingPhysician <- APH -- : MedicalRecord

AttendingPhysician -> APH ++ : confirmPhoneCallTowardsPatient(Patient, ThresholdAlert)
APH -> ThresholdAlertDS ++ : storeThresholdAlert(ThresholdAlert)
APH <- ThresholdAlertDS -- : confirmation
AttendingPhysician <- APH -- : confirmation

AttendingPhysician -> APH ++ : defineTherapeuticPlan(TherapeuticPlan)
APH -> PS ++ : updatePhysiologicalFrequencies(Frequencies)
deactivate PS
APH -> MedicalRecordDS ++ : createTherapeuticPlan(TherapeuticPlan)
APH <- MedicalRecordDS -- : confirmation

AttendingPhysician <- APH -- : confirmation

AttendingPhysician -> APH ++ : modifyTherapeuticPlan(TherapeuticPlan)
alt Frequencies changed?
  APH -> PS ++ : updatePhysiologicalFrequencies(Frequencies)
  deactivate PS
end
APH -> MedicalRecordDS ++ : storeTherapeuticPlan(TherapeuticPlan)
APH <- MedicalRecordDS -- : confirmation
AttendingPhysician <- APH -- : confirmation


@enduml
