@startuml patient_handler

skinparam sequence {
  ArrowColor Gray
  LifeLineBorderColor Gray
  LifeLineBackgroundColor WhiteSmoke

  ActorBorderColor Tomato
  ActorBackgroundColor LightSalmon

  ParticipantBackgroundColor PowderBlue
  ParticipantBorderColor CornflowerBlue
}
skinparam DatabaseBorderColor SeaGreen
skinparam DatabaseBackgroundColor PaleGreen

actor Patient
participant PatientHandler as PH
database TherapeuticPlanDS
database PhysiologicalDataDS
participant ProcessDataHandler as PDH

Patient -> PH ++ : viewTherapeuticPlan()
PH -> TherapeuticPlanDS ++ : getTherapeuticPlan(patientId)
PH <- TherapeuticPlanDS -- : TherapeuticPlan
PH -> Patient -- : displayTherapeuticPlan(TherapeuticPlan)

Patient -> PH ++ : sendPhysiologicalData(PhysiologicalData)

PH -> PhysiologicalDataDS ++ : storePhysiologicalData(PhysiologicalData)
PH <- PhysiologicalDataDS -- : confirmation

PH -> PDH ++ : sendToProcessDataHandler(PhysiologicalData)
deactivate PDH
Patient <- PH -- : confirmation
