@startuml process_data_handler

skinparam sequence {
ArrowColor Gray
LifeLineBorderColor Gray
LifeLineBackgroundColor WhiteSmoke

ActorBorderColor Tomato
ActorBackgroundColor LightSalmon

ParticipantBackgroundColor PowderBlue
ParticipantBorderColor CornflowerBlue
}
skinparam DatabaseBorderColor SeaGreen
skinparam DatabaseBackgroundColor PaleGreen

participant PatientHandler as PH
participant SensorDataHandler as SDH1
participant SensorDataHandler as SDH2
participant ProcessDataHandler as PDH
participant AlertsHandler as AH
participant ProcessDataHandlerThread as PDH1
participant ProcessDataHandlerThread as PDH2
participant ProcessDataHandlerThread as PDH3

PH -> PDH ++ : processPatientData(Patient, PhysiologicalData)

PDH -> PDH1 ** : startProcessPatientData(Patient, PhysiologicalData)
deactivate PDH

alt RedCode detected
PDH1 -> AH ++ : sendIdentifyHospitalAndAmbulance(Patient)
deactivate AH
else Anomaly detected
PDH1 -> AH ++ : sendIdentifyOnCallPhysician(Patient, Anomaly)
deactivate AH
else Threshold exceeded
PDH1 -> AH ++ : sendThresholdAlertAndPatientNumber(Patient, TherapeuticPlan, Threshold)
deactivate AH
end

SDH1 -> PDH ++ : processPatientData(PhysiologicalData)

PDH -> PDH2 ** : startProcessPatientData(Patient, PhysiologicalData)
deactivate PDH

alt RedCode detected
PDH2 -> AH ++ : sendIdentifyHospitalAndAmbulance(Patient)
deactivate AH
else Anomaly detected
PDH2 -> AH ++ : sendIdentifyOnCallPhysician(Patient, Anomaly)
deactivate AH
else Threshold exceeded
PDH2 -> AH ++ : sendThresholdAlertAndPatientNumber(Patient, TherapeuticPlan, Threshold)
deactivate AH
end

SDH2 -> PDH ++ : processPatientData(DailyActivityData)

PDH -> PDH3 ** : startProcessPatientData(Patient, PhysiologicalData)
deactivate PDH

alt RedCode detected
PDH3 -> AH ++ : sendIdentifyHospitalAndAmbulance(Patient)
deactivate AH
else Anomaly detected
PDH3 -> AH ++ : sendIdentifyOnCallPhysician(Patient, Anomaly)
deactivate AH
else Threshold exceeded
PDH3 -> AH ++ : sendThresholdAlertAndPatientNumber(Patient, TherapeuticPlan, Threshold)
deactivate AH
end

deactivate PDH

@enduml
