@startuml alerts
actor PhysiologicalSensor as PS
actor DailyActivityPlatform as DAP
participant SensorDataHandler as SDH
participant SensorDataThread as SDT1
participant SensorDataThread as SDT2
participant ProcessDataHandler as PDH
database DailyActivityDS
database PhysiologicalDataDS


PS -> SDH : sendPhysiologicalData(PhysiologicalData)
activate SDH

SDH -> SDT1 ** : startStorePhysiologicalData(PhysiologicalData)
activate SDT1
SDT1 -> PhysiologicalDataDS ++ : storePhysiologicalData(PhysiologicalData)
SDT1 <- PhysiologicalDataDS --

deactivate SDT1

SDH -> SDT2 ** : startHandlePhysiologicalData(PhysiologicalData)
activate SDT2
SDT2 -> PDH ++ : sendToProcessDataHandler(PhysiologicalData)
deactivate PDH
deactivate SDT2
deactivate SDH

DAP -> SDH : sendDailyActivityData(DailyActivityData)
activate SDH

SDH -> SDT1 ** : startStoreDailyActivityData(DailyActivityData)
activate SDT1
SDT1 -> DailyActivityDS ++ : storeDailyActivityData(DailyActivityData)
SDT1 <- DailyActivityDS --

deactivate SDT1

SDH -> SDT2 ** : startHandleDailyActivityData(DailyActivityData)
activate SDT2
SDT2 -> PDH ++ : sendToProcessDataHandler(DailyActivityData)
deactivate PDH
deactivate SDT2
deactivate SDH
