@startuml sensors_data_handler

skinparam sequence {
ArrowColor Gray
LifeLineBorderColor Gray
LifeLineBackgroundColor WhiteSmoke

ActorBorderColor Tomato
ActorBackgroundColor LightSalmon

ParticipantBackgroundColor PowderBlue
ParticipantBorderColor CornflowerBlue
}
skinparam DatabaseBorderColor SeaGreen
skinparam DatabaseBackgroundColor PaleGreen

actor PhysiologicalSensor as PS
actor DailyActivityPlatform as DAP
participant SensorDataHandler as SDH
participant ProcessDataHandler as PDH
participant SensorDataThread as SDT1
participant SensorDataThread as SDT2
database PhysiologicalDataDS
database DailyActivityDS


PS -> SDH : sendPhysiologicalData(PhysiologicalData)
activate SDH

SDH -> SDT1 ** : startStorePhysiologicalData(PhysiologicalData)
activate SDT1
SDT1 -> PhysiologicalDataDS ++ : storePhysiologicalData(PhysiologicalData)
SDT1 <- PhysiologicalDataDS -- : confirmation

deactivate SDT1

SDH -> SDT2 ** : startHandlePhysiologicalData(PhysiologicalData)
activate SDT2
SDT2 -> PDH ++ : sendToProcessDataHandler(PhysiologicalData)
deactivate SDT2
deactivate PDH
deactivate SDH

DAP -> SDH : sendDailyActivityData(DailyActivityData)
activate SDH

SDH -> SDT1 ** : startStoreDailyActivityData(DailyActivityData)
activate SDT1
SDT1 -> DailyActivityDS ++ : storeDailyActivityData(DailyActivityData)
SDT1 <- DailyActivityDS -- : confirmation

deactivate SDT1

SDH -> SDT2 ** : startHandleDailyActivityData(DailyActivityData)
activate SDT2
SDT2 -> PDH ++ : sendToProcessDataHandler(DailyActivityData)
deactivate SDT2
deactivate PDH
deactivate SDH
