@startuml verify_exercise_compliance

skinparam sequence {
  ArrowColor Gray
  LifeLineBorderColor Gray
  LifeLineBackgroundColor WhiteSmoke

  ActorBorderColor Tomato
  ActorBackgroundColor LightSalmon

  ParticipantBackgroundColor PowderBlue
  ParticipantBorderColor CornflowerBlue
}
skinparam DatabaseBorderColor SeaGreen
skinparam DatabaseBackgroundColor PaleGreen

hide footbox

participant ExerciseComplianceHandler as ECH
participant AlertHandler as AH
database PatientDS
database DailyActivityDS
database TherapeuticPlanDS

activate ECH
ECH -> PatientDS ++ : getPatients()
ECH <- PatientDS -- : patientsList

loop for each patient
  ECH -> DailyActivityDS ++ : getDailyActivityData(Patient)
  ECH <- DailyActivityDS -- : DailyActivityData[]
  ECH -> TherapeuticPlanDS ++ : getTherapeuticPlan(Patient)
  ECH <- TherapeuticPlanDS -- : TherapeuticPlan

  ECH -> ECH : verifyExerciseCompliance(TherapeuticPlan, DailyActivityData[])
  activate ECH
  alt (is threshold exceeded)
    ECH -> AH ++ : sendThresholdAlert(Patient, Threshold)
    deactivate AH
  end
  deactivate ECH
end

deactivate ECH

@enduml
