@startuml concrete_diagram

skinparam ClassBorderColor CornflowerBlue
skinparam ClassBackgroundColor PowderBlue

class "<<Sequential>> Sensors and Data Handler" as C1 {
  <<Async, Push>>
  + pushPhysiologicalData(PhysiologicalData): void
  + pushDailyActivityData(DailyActivityData): void
}

class "<<Concurrent>> Alerts Handler" as C2 {
  +identifyHospitalAndAmbulance(Patient)
  +identifyOnCallPhysician(Patient)
  <<Async>>
  -sendHospitalAlert(Hospital)
  -sendAmbulanceAlert(Ambulance, Address)
  -notifyOnCallPhysician(OnCallPhysician, Anomaly)
  +sendThresholdAlert(AttendingPhysician, Threshold)
}

class "<<Sequential>> Patient Handler" as C3 {
  +sendPhysiologicalData(PhysiologicalData)
  +viewTherapeuticPlan(Patient) <<Sync, Pull>>
}

class "<<Sequential>> On Call Physician Handler" as C4 {
  +sendDiagnosticInformation(DiagnosticInformation)
  +sendPatientHealthInfo(PatientHealthInfo)
}

class "<<Sequential>> Attending Physician Handler" as C5 {
  -configureSensorFrequencies(Frequency[]) <<Async, Push>>
  +defineTherapeuticPlan(Patient, TherapeuticPlan)
  +modifyTherapeuticPlan(Patient, TherapeuticPlan)
  +viewPatientMedicalRecord(Patient)
  +confirmPhoneCallTowardsPatient(Patient, Anomaly)
}

class "<<Concurrent>> Patient Data Handler" as C6 {
  <<Async, Push>>
  +processPatientData(Patient, PatientData)
  +processSensorsData(PhysiologicalData)
  +processDailyActivityData(DailiActivityData)
}

class "<<OneShot>> Verify Exercise Compliance Handler" as C7 {
  +verifyExerciseCompliance()
}

@enduml
