@startuml deployment_architecture

skinparam NodeBorderColor gold
skinparam NodeBackgroundColor %lighten(gold, 50)

skinparam FrameBorderColor gray
skinparam FrameBackgroundColor whitesmoke

skinparam DatabaseBorderColor %darken(plum, 50)
skinparam DatabaseBackgroundColor plum

skinparam ComponentBorderColor %darken(PaleTurquoise, 50)
skinparam ComponentBackgroundColor PaleTurquoise

!pragma layout elk
left to right direction

node "<<device>>\n(N) Attending Physician" as Attending_Physician_1_1
node "<<device>>\n(N) On Call Physician" as On_Call_Physician_1_1

frame Hospital_1 {
    component "Alerts Handler" as AH1
    component "Alerts Handler Hot Spare" as AH1B
    component "Attending Physician Handler" as APH1
    component "On Call Physician Handler" as OCPH1

    component "Patient Data Handler" as PDH1
    component "Patient Data Handler Hot Spare" as PDH1B
    component "Verify Exercise Compliance Handler" as VECH1
    database "Storage" as DS1

    PDH1 --> DS1 : <<use>>
    VECH1 --> DS1 : <<use>>
}

frame Edge_1 {
    component "Sensors and Data Handler" as SDH1
    component "Patient Handler" as PH1
}

frame Edge_2 {
    component "Sensors and Data Handler" as SDH2
    component "Patient Handler" as PH2
}

frame Edge_N {
    component "Sensors and Data Handler" as SDH3
    component "Patient Handler" as PH3
}

together {
    node "<<device>>\n(N) Sensor" as Sensor_1_1
    node "<<device>>\n(N) Daily Activity Platform" as DAP_1_1
    node "<<device>>\n(N) Patient" as Patient_1_1


    Sensor_1_1 -> Edge_1 : HTTPS
    DAP_1_1 -> Edge_1 : HTTPS
    Patient_1_1 -> Edge_1 : HTTPS
}

Edge_1 -> Hospital_1 : HTTPS

Attending_Physician_1_1 --> Hospital_1 : VPN+HTTPS
On_Call_Physician_1_1 --> Hospital_1 : VPN+HTTPS

node "<<device>>\n(N) Attending Physician" as Attending_Physician_1_2
node "<<device>>\n(N) On Call Physician" as On_Call_Physician_1_2


frame Hospital_N {
    component "Alerts Handler" as AH2
    component "Alerts Handler Hot Spare" as AH2B
    component "Attending Physician Handler" as APH2
    component "On Call Physician Handler" as OCPH2

    component "Patient Data Handler" as PDH2
    component "Patient Data Handler Hot Spare" as PDH2B
    component "Verify Exercise Compliance Handler" as VECH2
    database "Storage" as DS2

    PDH2 --> DS2 : <<use>>
    VECH2 --> DS2 : <<use>>
}

Attending_Physician_1_2 --> Hospital_N : VPN+HTTPS
On_Call_Physician_1_2 --> Hospital_N : VPN+HTTPS



node "<<device>>\n(N) Sensor" as Sensor_1_2
node "<<device>>\n(N) Daily Activity Platform" as DAP_1_2
node "<<device>>\n(N) Patient" as Patient_1_2

Sensor_1_2 -> Edge_2 : HTTPS
DAP_1_2 -> Edge_2 : HTTPS
Patient_1_2 -> Edge_2 : HTTPS

node "<<device>>\n(N) Sensor" as Sensor_1_3
node "<<device>>\n(N) Daily Activity Platform" as DAP_1_3
node "<<device>>\n(N) Patient" as Patient_1_3

Sensor_1_3 -> Edge_N : HTTPS
DAP_1_3 -> Edge_N : HTTPS
Patient_1_3 -> Edge_N : HTTPS

Edge_2 -> Hospital_N : HTTPS
Edge_N -> Hospital_N : HTTPS

@enduml
